// Mocks generated by Mockito 5.4.5 from annotations
// in ewc/test/login_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:ewc/screens/map/map.dart' as _i10;
import 'package:ewc/services/auth_service.dart' as _i7;
import 'package:ewc/services/encryption_service.dart' as _i2;
import 'package:flutter/foundation.dart' as _i6;
import 'package:flutter/material.dart' as _i5;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i3;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEncryptionService_0 extends _i1.SmartFake
    implements _i2.EncryptionService {
  _FakeEncryptionService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFlutterSecureStorage_1 extends _i1.SmartFake
    implements _i3.FlutterSecureStorage {
  _FakeFlutterSecureStorage_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_2 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeState_3<T extends _i5.StatefulWidget> extends _i1.SmartFake
    implements _i5.State<T> {
  _FakeState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeStatefulElement_4 extends _i1.SmartFake
    implements _i5.StatefulElement {
  _FakeStatefulElement_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_5 extends _i1.SmartFake
    implements _i5.DiagnosticsNode {
  _FakeDiagnosticsNode_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({
    _i6.TextTreeConfiguration? parentConfiguration,
    _i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info,
  }) => super.toString();
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i7.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EncryptionService get encryptionService =>
      (super.noSuchMethod(
            Invocation.getter(#encryptionService),
            returnValue: _FakeEncryptionService_0(
              this,
              Invocation.getter(#encryptionService),
            ),
          )
          as _i2.EncryptionService);

  @override
  _i3.FlutterSecureStorage get authStorage =>
      (super.noSuchMethod(
            Invocation.getter(#authStorage),
            returnValue: _FakeFlutterSecureStorage_1(
              this,
              Invocation.getter(#authStorage),
            ),
          )
          as _i3.FlutterSecureStorage);

  @override
  String get apiUrl =>
      (super.noSuchMethod(
            Invocation.getter(#apiUrl),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#apiUrl),
            ),
          )
          as String);

  @override
  String get adminUrl =>
      (super.noSuchMethod(
            Invocation.getter(#adminUrl),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#adminUrl),
            ),
          )
          as String);

  @override
  _i9.Future<void> initializeAuthService() =>
      (super.noSuchMethod(
            Invocation.method(#initializeAuthService, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> saveUserCredentials(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserCredentials, [username, password]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<Map<String, String?>> loadUserCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#loadUserCredentials, []),
            returnValue: _i9.Future<Map<String, String?>>.value(
              <String, String?>{},
            ),
          )
          as _i9.Future<Map<String, String?>>);

  @override
  _i9.Future<void> clearCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#clearCredentials, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<bool> checkEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#checkEmail, [email]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> refreshAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshAccessToken, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i4.Response> makeAuthenticatedRequest(String? endpoint) =>
      (super.noSuchMethod(
            Invocation.method(#makeAuthenticatedRequest, [endpoint]),
            returnValue: _i9.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(#makeAuthenticatedRequest, [endpoint]),
              ),
            ),
          )
          as _i9.Future<_i4.Response>);

  @override
  _i9.Future<void> register({
    required String? username,
    required String? password,
    required dynamic email,
    required dynamic phoneNumber,
    required dynamic address,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #username: username,
              #password: password,
              #email: email,
              #phoneNumber: phoneNumber,
              #address: address,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [MapPage].
///
/// See the documentation for Mockito's code generation for more information.
class MockMapPage extends _i1.Mock implements _i10.MapPage {
  MockMapPage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.State<_i10.MapPage> createState() =>
      (super.noSuchMethod(
            Invocation.method(#createState, []),
            returnValue: _FakeState_3<_i10.MapPage>(
              this,
              Invocation.method(#createState, []),
            ),
          )
          as _i5.State<_i10.MapPage>);

  @override
  _i5.StatefulElement createElement() =>
      (super.noSuchMethod(
            Invocation.method(#createElement, []),
            returnValue: _FakeStatefulElement_4(
              this,
              Invocation.method(#createElement, []),
            ),
          )
          as _i5.StatefulElement);

  @override
  String toStringShort() =>
      (super.noSuchMethod(
            Invocation.method(#toStringShort, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#toStringShort, []),
            ),
          )
          as String);

  @override
  void debugFillProperties(_i6.DiagnosticPropertiesBuilder? properties) =>
      super.noSuchMethod(
        Invocation.method(#debugFillProperties, [properties]),
        returnValueForMissingStub: null,
      );

  @override
  String toStringShallow({
    String? joiner = ', ',
    _i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.debug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toStringShallow, [], {
              #joiner: joiner,
              #minLevel: minLevel,
            }),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#toStringShallow, [], {
                #joiner: joiner,
                #minLevel: minLevel,
              }),
            ),
          )
          as String);

  @override
  String toStringDeep({
    String? prefixLineOne = '',
    String? prefixOtherLines,
    _i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.debug,
    int? wrapWidth = 65,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toStringDeep, [], {
              #prefixLineOne: prefixLineOne,
              #prefixOtherLines: prefixOtherLines,
              #minLevel: minLevel,
              #wrapWidth: wrapWidth,
            }),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#toStringDeep, [], {
                #prefixLineOne: prefixLineOne,
                #prefixOtherLines: prefixOtherLines,
                #minLevel: minLevel,
                #wrapWidth: wrapWidth,
              }),
            ),
          )
          as String);

  @override
  _i5.DiagnosticsNode toDiagnosticsNode({
    String? name,
    _i6.DiagnosticsTreeStyle? style,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toDiagnosticsNode, [], {
              #name: name,
              #style: style,
            }),
            returnValue: _FakeDiagnosticsNode_5(
              this,
              Invocation.method(#toDiagnosticsNode, [], {
                #name: name,
                #style: style,
              }),
            ),
          )
          as _i5.DiagnosticsNode);

  @override
  List<_i5.DiagnosticsNode> debugDescribeChildren() =>
      (super.noSuchMethod(
            Invocation.method(#debugDescribeChildren, []),
            returnValue: <_i5.DiagnosticsNode>[],
          )
          as List<_i5.DiagnosticsNode>);

  @override
  String toString({_i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info}) =>
      super.toString();
}
