// Mocks generated by Mockito 5.4.5 from annotations
// in ewc/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:ewc/models/stop_model.dart' as _i12;
import 'package:ewc/screens/map/map.dart' as _i15;
import 'package:ewc/screens/metrics/route_data.dart' as _i14;
import 'package:ewc/services/auth_service/auth_service.dart' as _i9;
import 'package:ewc/services/auth_service/encryption_service.dart' as _i2;
import 'package:ewc/services/metrics_service.dart' as _i13;
import 'package:ewc/services/route_service.dart' as _i7;
import 'package:ewc/services/stops_service.dart' as _i6;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i3;
import 'package:http/http.dart' as _i4;
import 'package:latlong2/latlong.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:open_route_service/open_route_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEncryptionService_0 extends _i1.SmartFake
    implements _i2.EncryptionService {
  _FakeEncryptionService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFlutterSecureStorage_1 extends _i1.SmartFake
    implements _i3.FlutterSecureStorage {
  _FakeFlutterSecureStorage_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_2 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOpenRouteService_3 extends _i1.SmartFake
    implements _i5.OpenRouteService {
  _FakeOpenRouteService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStopsService_4 extends _i1.SmartFake implements _i6.StopsService {
  _FakeStopsService_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteResult_5 extends _i1.SmartFake implements _i7.RouteResult {
  _FakeRouteResult_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLatLng_6 extends _i1.SmartFake implements _i8.LatLng {
  _FakeLatLng_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i9.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EncryptionService get encryptionService =>
      (super.noSuchMethod(
            Invocation.getter(#encryptionService),
            returnValue: _FakeEncryptionService_0(
              this,
              Invocation.getter(#encryptionService),
            ),
          )
          as _i2.EncryptionService);

  @override
  _i3.FlutterSecureStorage get authStorage =>
      (super.noSuchMethod(
            Invocation.getter(#authStorage),
            returnValue: _FakeFlutterSecureStorage_1(
              this,
              Invocation.getter(#authStorage),
            ),
          )
          as _i3.FlutterSecureStorage);

  @override
  String get siteUrl =>
      (super.noSuchMethod(
            Invocation.getter(#siteUrl),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#siteUrl),
            ),
          )
          as String);

  @override
  String get adminUrl =>
      (super.noSuchMethod(
            Invocation.getter(#adminUrl),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#adminUrl),
            ),
          )
          as String);

  @override
  _i11.Future<void> initializeAuthService() =>
      (super.noSuchMethod(
            Invocation.method(#initializeAuthService, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> saveUserCredentials(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserCredentials, [username, password]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<Map<String, String?>> loadUserCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#loadUserCredentials, []),
            returnValue: _i11.Future<Map<String, String?>>.value(
              <String, String?>{},
            ),
          )
          as _i11.Future<Map<String, String?>>);

  @override
  _i11.Future<void> clearCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#clearCredentials, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<bool> checkEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#checkEmail, [email]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<void> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> refreshAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshAccessToken, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i4.Response> makeAuthenticatedRequest(String? endpoint) =>
      (super.noSuchMethod(
            Invocation.method(#makeAuthenticatedRequest, [endpoint]),
            returnValue: _i11.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(#makeAuthenticatedRequest, [endpoint]),
              ),
            ),
          )
          as _i11.Future<_i4.Response>);

  @override
  _i11.Future<_i4.Response> makeAuthenticatedPostRequest(
    String? endpoint,
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#makeAuthenticatedPostRequest, [endpoint, body]),
            returnValue: _i11.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(#makeAuthenticatedPostRequest, [
                  endpoint,
                  body,
                ]),
              ),
            ),
          )
          as _i11.Future<_i4.Response>);

  @override
  _i11.Future<void> register({
    required String? username,
    required String? password,
    required dynamic email,
    required dynamic phoneNumber,
    required dynamic address,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #username: username,
              #password: password,
              #email: email,
              #phoneNumber: phoneNumber,
              #address: address,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void launchPasswordReset() => super.noSuchMethod(
    Invocation.method(#launchPasswordReset, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [RouteService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouteService extends _i1.Mock implements _i7.RouteService {
  MockRouteService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.OpenRouteService get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeOpenRouteService_3(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i5.OpenRouteService);

  @override
  _i6.StopsService get stopsService =>
      (super.noSuchMethod(
            Invocation.getter(#stopsService),
            returnValue: _FakeStopsService_4(
              this,
              Invocation.getter(#stopsService),
            ),
          )
          as _i6.StopsService);

  @override
  _i11.Future<List<_i8.LatLng>> getRoute(
    double? startLat,
    double? startLng,
    double? endLat,
    double? endLng,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRoute, [startLat, startLng, endLat, endLng]),
            returnValue: _i11.Future<List<_i8.LatLng>>.value(<_i8.LatLng>[]),
          )
          as _i11.Future<List<_i8.LatLng>>);

  @override
  _i11.Future<_i7.RouteResult> routePlanning(
    _i8.LatLng? userLocation,
    List<_i12.Stop>? stops,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#routePlanning, [userLocation, stops]),
            returnValue: _i11.Future<_i7.RouteResult>.value(
              _FakeRouteResult_5(
                this,
                Invocation.method(#routePlanning, [userLocation, stops]),
              ),
            ),
          )
          as _i11.Future<_i7.RouteResult>);

  @override
  _i11.Future<List<int>> getStopTimes(
    _i8.LatLng? source,
    List<_i8.LatLng>? stopLocations,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getStopTimes, [source, stopLocations]),
            returnValue: _i11.Future<List<int>>.value(<int>[]),
          )
          as _i11.Future<List<int>>);

  @override
  double distanceFromSegment(
    _i8.LatLng? location,
    _i8.LatLng? startPoint,
    _i8.LatLng? endPoint,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#distanceFromSegment, [
              location,
              startPoint,
              endPoint,
            ]),
            returnValue: 0.0,
          )
          as double);
}

/// A class which mocks [StopsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStopsService extends _i1.Mock implements _i6.StopsService {
  MockStopsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<void> postStopCollection(int? stopID, int? weightCollected) =>
      (super.noSuchMethod(
            Invocation.method(#postStopCollection, [stopID, weightCollected]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i8.LatLng> fetchStop(int? stopID) =>
      (super.noSuchMethod(
            Invocation.method(#fetchStop, [stopID]),
            returnValue: _i11.Future<_i8.LatLng>.value(
              _FakeLatLng_6(this, Invocation.method(#fetchStop, [stopID])),
            ),
          )
          as _i11.Future<_i8.LatLng>);

  @override
  _i11.Future<List<_i12.Stop>> fetchAllStops() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllStops, []),
            returnValue: _i11.Future<List<_i12.Stop>>.value(<_i12.Stop>[]),
          )
          as _i11.Future<List<_i12.Stop>>);
}

/// A class which mocks [MetricsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMetricsService extends _i1.Mock implements _i13.MetricsService {
  MockMetricsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<List<_i14.JourneyRoute>> fetchAllRoutes() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllRoutes, []),
            returnValue: _i11.Future<List<_i14.JourneyRoute>>.value(
              <_i14.JourneyRoute>[],
            ),
          )
          as _i11.Future<List<_i14.JourneyRoute>>);
}

/// A class which mocks [Config].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfig extends _i1.Mock implements _i15.Config {
  MockConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get inTestMode =>
      (super.noSuchMethod(Invocation.getter(#inTestMode), returnValue: false)
          as bool);

  @override
  set inTestMode(bool? _inTestMode) => super.noSuchMethod(
    Invocation.setter(#inTestMode, _inTestMode),
    returnValueForMissingStub: null,
  );
}
