version: "3.8"

services:
  ewc_backend:
    build: .
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    restart: unless-stopped
    container_name: ewc_backend_container
    command: gunicorn ewc_admin.wsgi:application --bind 0.0.0.0:8000
