# Generated by Django 5.1.2 on 2025-02-11 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteEnvData',
            fields=[
                ('route_env_data_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('distance', models.FloatField()),
                ('mpg', models.FloatField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'ewc_core_route_env_data',
            },
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('stop_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('next_collection_due_date', models.DateField(blank=True, null=True)),
                ('max_weight', models.IntegerField()),
            ],
            options={
                'db_table': 'ewc_core_stops',
            },
        ),
        migrations.CreateModel(
            name='StopCollection',
            fields=[
                ('stop_collection_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('weight_collected', models.IntegerField()),
                ('date', models.DateField()),
                ('stop', models.ForeignKey(db_column='stop_id', on_delete=django.db.models.deletion.DO_NOTHING, to='ewc_core.stops')),
            ],
            options={
                'db_table': 'ewc_core_stop_collection',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('pickup_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('waste_type_preference', models.CharField(choices=[('general', 'General'), ('recycling', 'Recycling'), ('organic', 'Organic')], default='general', max_length=20)),
                ('carbon_savings', models.FloatField(default=0.0)),
                ('notification_preferences', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
