# Generated by Django 5.1.2 on 2024-10-18 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # Specifies that this is the initial migration
    initial = True

    # Defines the dependencies for the migration
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Defines the operations (changes) to be applied to the database
    operations = [
        # Create the CollectionPoint model/table in the database
        migrations.CreateModel(
            name="CollectionPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                # Adds fields for location name, latitude, longitude, and address
                ("location_name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("address", models.CharField(max_length=255)),
            ],
        ),
        # Create the JourneyMetric model/table in the database
        migrations.CreateModel(
            name="JourneyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                # Adds fields for CO2 emissions, fuel used, distance traveled, and journey date
                ("co2_emissions", models.FloatField()),
                ("fuel_used", models.FloatField()),
                ("distance_traveled", models.FloatField()),
                ("journey_date", models.DateTimeField(auto_now_add=True)),
                # Foreign key relationship to the CollectionPoint model
                (
                    "collection_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ewc_web.collectionpoint",
                    ),
                ),
                # Foreign key relationship to the User model
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        # Create the WastePrediction model/table in the database
        migrations.CreateModel(
            name="WastePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                # Adds fields for predicted weight, predicted date, and actual weight (optional)
                ("predicted_weight", models.FloatField()),
                ("predicted_date", models.DateField()),
                ("actual_weight", models.FloatField(blank=True, null=True)),
                # Foreign key relationship to the CollectionPoint model
                (
                    "collection_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ewc_web.collectionpoint",
                    ),
                ),
            ],
        ),
    ]
