# Generated by Django 5.1.2 on 2025-02-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewc_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeenvdata',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
