# Generated by Django 5.1.2 on 2025-02-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewc_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopcollection',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
