# Generated by Django 5.1.2 on 2025-02-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewc_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stops',
            name='last_collection_date',
        ),
        migrations.AddField(
            model_name='stopcollection',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routeenvdata',
            name='date',
            field=models.DateField(),
        ),
    ]
