# Generated by Django 5.1.2 on 2025-02-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewc_core', '0002_alter_routeenvdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeenvdata',
            name='date',
            field=models.DateField(),
        ),
    ]
