# Generated by Django 5.1.2 on 2025-02-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewc_core', '0002_alter_stopcollection_date'),
        ('ewc_core', '0003_alter_routeenvdata_date'),
    ]

    operations = [
    ]
