# Generated by Django 5.1.2 on 2025-03-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewc_core', '0004_merge_20250224_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stops',
            options={'verbose_name': 'Stop', 'verbose_name_plural': 'Stops'},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='email_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='carbon_savings',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_preferences',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pickup_frequency',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='waste_type_preference',
        ),
    ]
