# Generated by Django 5.1.2 on 2025-03-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewc_core', '0005_alter_stops_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stops',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
