# Generated by Django 5.1.2 on 2025-03-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewc_core', '0007_depo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depo',
            options={'verbose_name': 'Singleton', 'verbose_name_plural': 'Singleton'},
        ),
    ]
