# Generated by Django 5.1.2 on 2025-03-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewc_core', '0008_alter_depo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depo',
            options={'verbose_name': 'Depo Location', 'verbose_name_plural': 'Singleton'},
        ),
        migrations.AddField(
            model_name='depo',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
