# Generated by Django 5.1.2 on 2025-03-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewc_core', '0009_alter_depo_options_depo_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depo',
            options={'verbose_name': 'Depo Location', 'verbose_name_plural': 'Depo Location'},
        ),
    ]
