# Generated by Django 5.1.2 on 2025-03-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewc_core', '0010_alter_depo_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Depo',
            new_name='Depot',
        ),
        migrations.AlterModelOptions(
            name='depot',
            options={'verbose_name': 'Depot Location', 'verbose_name_plural': 'Depot Location'},
        ),
    ]
