name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-linux
    defaults:
        run:
          working-directory: "./ewc-app"    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup and Install Flutter
        uses: subosito/flutter-action@v2
      - name: Install Flutter Dependencies
        run: flutter pub get
      - name: Run Static Code Analysis
        run : flutter analyze
      - name: Run Flutter Tests
        run: flutter test
  ios-test:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup and Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: Enable iOS
        run: flutter config --enable-ios
      - name: Install Flutter Dependencies
        run: flutter pub get
      - name: Run Flutter Static Code Analysis
        run: flutter analyze
      - name: Run Flutter Unit and Widget Tests
        run: flutter test test
      - name: Run Flutter Integration Tests
        run: |
          xcrun simctl boot "iPhone 16"
          flutter test integration_test -d "iPhone 16"
      - name: Build Flutter App
        run: flutter build ios --no-codesign

  android-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level:
          - "34"
          - "35"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup and Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: Enable Android
        run: flutter config --enable-android
      - name: Install Flutter Dependencies
        run: flutter pub get
      - name: Run Flutter Static Code Analysis
        run: flutter analyze
      - name: Run Flutter Unit and Widget Tests
        run: flutter test test
      - name: Run Flutter Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: pixel_6_pro
          script: flutter test integration_test
      - name: Build Flutter App
        run: flutter build apk --debug