name: CD - Build and Push Django Docker Image to ECR

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    name: Build and Push Backend Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set Environment Variables
        run: |
          echo "REPO_URI=713881812987.dkr.ecr.eu-west-2.amazonaws.com/ewc-django-docker" >> .env
          echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> .env

      - name: Build Docker Image with Docker Compose
        run: |
          cd ewc_backend
          cat .env
          docker compose build
          docker tag ewc_backend_ewc_backend $REPO_URI:$IMAGE_TAG
          docker tag ewc_backend_ewc_backend $REPO_URI:latest

      - name: Push Docker Image to AWS ECR
        run: |
          docker push $REPO_URI:$IMAGE_TAG
          docker push $REPO_URI:latest

      - name: Output Image URI
        run: echo "Image pushed to $REPO_URI:latest"
