name: CD - Build and Push Django Docker Image to ECR

on:
  push:


jobs:
  build-and-push:
    name: Build and Push Backend Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Tag Docker Image
        run: |


          REPO_URI=713881812987.dkr.ecr.eu-west-2.amazonaws.com/ewc-django-docker
          IMAGE_TAG=$(git rev-parse --short HEAD)

          cd ewc_backend
          DOCKER_BUILDKIT=1 docker build \
            --secret id=django_secret_key,env=DJANGO_SECRET_KEY \
            --secret id=postgres_db,env=POSTGRES_DB \
            --secret id=postgres_user,env=POSTGRES_USER \
            --secret id=postgres_password,env=POSTGRES_PASSWORD \
            --secret id=postgres_host,env=POSTGRES_HOST \
            --secret id=postgres_port,env=POSTGRES_PORT \
            --secret id=sendgrid_secret_key,env=SENDGRID_SECRET_KEY \
            -t $REPO_URI:$IMAGE_TAG .

          docker tag $REPO_URI:$IMAGE_TAG $REPO_URI:latest

          docker run --rm $REPO_URI:$IMAGE_TAG ls /app/staticfiles

      - name: Push Docker Image to AWS ECR
        run: |
          REPO_URI=713881812987.dkr.ecr.eu-west-2.amazonaws.com/ewc-django-docker
          IMAGE_TAG=$(git rev-parse --short HEAD)
          docker push $REPO_URI:$IMAGE_TAG
          docker push $REPO_URI:latest

      - name: Output Image URI
        run: echo "Image pushed to $REPO_URI:latest"
